### ISSUE TITLE
Error Message with the rv option

### ISSUE THREAD

**Issue by guilhemc** [wbuchanan/StataJSON#25]
Hi,

the rv option gives me an error message:

jsonio rv, file(http://api.nightlights.io/months/1993.3-2013.12/villages/709000300016300)
gives me:
java.lang.ArrayIndexOutOfBoundsException: 3
at org.paces.Stata.Input.InJSON.insheetUrlToVars(InJSON.java:214)

while the kv option works fine.
Would you happen to know what may be causing the issue ?
Many thanks,

**Comment by wbuchanan** [comment]
@guilhemc 
This should be fixed on the dev branch of the repository.  I'll try to get a build put together and pushed to the gh-pages branch this weekend so users can reinstall with more ease.

**Comment by wbuchanan** [comment]
```Stata
net inst jsonio, from(http://wbuchanan.github.io/StataJSON) replace
```

That should take care of things now.
