### ISSUE TITLE
How do I download from PwWeb-based API with "Post"-function?

### ISSUE THREAD

**Issue by elektrotiko** [wbuchanan/StataJSON#36]
Hi

Is there a way to get jsonio to work with Pw-Web-based API that runs with "Post-"function?

See an example here: http://www.statistikdatabasen.scb.se/sq/85947

In the instruction for API, the website says:

"POST the following JSON query to the URL below to access this table from your application.
"
{
  "query": [
    {
      "code": "Region",
      "selection": {
        "filter": "vs:RegionKommun07",
        "values": [
          "0114",
          "0115"
        ]
      }
    },
    {
      "code": "Civilstand",
      "selection": {
        "filter": "item",
        "values": [
          "OG"
        ]
      }
    },
    {
      "code": "Alder",
      "selection": {
        "filter": "vs:ÅlderTotA",
        "values": [
          "tot"
        ]
      }
    },
    {
      "code": "ContentsCode",
      "selection": {
        "filter": "item",
        "values": [
          "BE0101N1"
        ]
      }
    },
    {
      "code": "Tid",
      "selection": {
        "filter": "item",
        "values": [
          "2019"
        ]
      }
    }
  ],
  "response": {
    "format": "px"
  }
}
"

How do I achieve this in jsonio?

**Comment by wbuchanan** [comment]
@elektrotiko 
I'm not sure about the architecture of the application you are attempting to connect to, but if it is a RESTful API you should be able to unfold all of the query parameters into a URL from which to specify the request.  There isn't currently any support for HTTP/S POST method calls when retrieving data from a URL.

**Comment by elektrotiko** [comment]
Thanks for a quick reply! Is there any other Stata package that has that functionality?

**Comment by wbuchanan** [comment]
@elektrotiko 
Sorry for the delayed response.  The best potential solution that might get you somewhere would probably involve using Curl from within Stata.  If you have StataOS installed (https://github.com/wbuchanan/StataOS) you might be able to parse things in a way that allows you to grab the result set fairly easily or could potentially write the result set directly to a file and then read it from disk.
